name: Jerry Bao
tagline: Software Engineer
description: Enthusiastic problem solver, tackling engineering challenges by day, flying airplanes by night.
meta_description: Who the hell cares about the meta description?

markdown: kramdown
highlighter: rouge
paginate: 5
baseurl: 'https://jerrybao.com'
domain_name: 'https://jerrybao.com'
google_analytics: 'UA-59441929-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://jerrybao.com'
author:         'Jerry Bao'
